import BaseEditLayout from 'formiojs/components/base/editForm/Base.edit.layout';
import { t } from '../../../../../helpers/export/util';

let attributesComponent = BaseEditLayout.find(item => item.key === 'attributes');

if (attributesComponent) {
  console.log('ATTRIBUTES COMPONENT', attributesComponent);
  // attributesComponent['keyLabel'] = 'Название атрибута'
  // attributesComponent = {
  //   ...attributesComponent,
  //   keyLabel: t('form-constructor.tabs-content.attributes.layout')
  // }
  // attributesComponent = {
  //   keyLabel: {
  //     ru: 'Название атрибута',
  //     en: 'Attribute Name'
  //   },
  //   ...attributesComponent
  // }

  attributesComponent = {
    label: 'HTML Attributes',
    type: 'datamap',
    input: true,
    key: 'attributes',
    keyLabel: {
      ru: 'Название атрибута',
      en: 'Attribute Name'
    },
    // get keyLabel() {
    //   return t('form-constructor.tabs-content.attributes.layout');
    // },
    valueComponent: {
      type: 'textfield',
      key: 'value',
      label: 'Attribute Value',
      input: true
    },
    tooltip:
      "Provide a map of HTML attributes for component's input element (attributes provided by other component settings or other attributes generated by form.io take precedence over attributes in this grid)",
    addAnother: 'Add Attribute'
  };
  console.log('ATTRIBUTES COMPONENT', attributesComponent);
}

export default BaseEditLayout;

// export default [
//   {
//     label: 'HTML Attributes',
//     type: 'datamap',
//     input: true,
//     key: 'attributes',
//     keyLabel: {
//       ru: 'Название атрибута',
//       en: 'Attribute Name'
//     },
//     valueComponent: {
//       type: 'textfield',
//       key: 'value',
//       label: 'Attribute Value',
//       input: true
//     },
//     tooltip: 'Provide a map of HTML attributes for component\'s input element (attributes provided by other component settings or other attributes generated by form.io take precedence over attributes in this grid)',
//     addAnother: 'Add Attribute',
//   }
// ];
