image: node:18.20-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .yarn/cache/

stages:
  - testing

testing:
  tags:
    - kuber-run-new
  stage: testing
  before_script:
    - yarn
  script:
    - yarn test:ci
  rules:
    - if: ($CI_PIPELINE_SOURCE == 'merge_request_event') && ($CI_PIPELINE_SOURCE != $CI_MERGE_REQUEST_DRAFT)
