version: '3'
services:
  community:
    ports:
    - 8443:8443/tcp
    environment:
    - DB_HOST=postgres
    - ALFRESCO_HOSTNAME=localhost
    - ALFRESCO_PROTOCOL=http
    - SHARE_HOSTNAME=localhost
    - SHARE_PROTOCOL=http
    - SHARE_PORT=8080
    - ALFRESCO_PORT=8080
    - FLOWABLE_URL=http://localhost
    - SOLR_STORE=/var/lib/solr4
    - MAIL_HOST=mailhog
    - MAIL_PORT=1025
    - DB_NAME=community_alfresco
    - FLOWABLE_DBNAME=community_flowable
    - JAVA_OPTS=-Djava.security.egd=file:///dev/urandom -Xmx2G
    volumes:
      - /opt/alfresco/license:/alfresco/tomcat/shared/classes/alfresco/ecos
      - /opt/alfresco/conf:/tmp/alfresco
      - /var/lib/solr4:/var/lib/solr4
      - /content:/content
    links:
    - postgres
    - mailhog
    tty: true
    hostname: ecos-demo-ru
    image: nexus.citeck.ru/ecos-community:3.8.0-snapshot
    stdin_open: true
    depends_on:
    - postgres
  postgres:
    environment:
    - POSTGRES_PASSWORD=alfr3sc0
    - DB_NAME=community_alfresco
    - FLOWABLE_DBNAME=community_flowable
    tty: true
    hostname: postgres
    image: nexus.citeck.ru/ecos-postgres:9.4-alpine
    stdin_open: true
    volumes:
      - /opt/alfresco/data/postgresql:/var/lib/postgresql/data
  mailhog:
    ports:
    - 8025:8025/tcp
    image: mailhog/mailhog
  ui:
    ports:
    - 80:80/tcp
    links:
    - community
    build:
      context: ./
      dockerfile: Dockerfile
