export const INSTANCE_TABS_TYPES = {
  VARIABLES: 'VARIABLES',
  INCIDENTS: 'INCIDENTS',
  CALLED_PROCESS: 'CALLED_PROCESS',
  JOB_DEFINITIONS: 'JOB_DEFINITIONS',
  EXTERNAL_TASKS: 'EXTERNAL_TASKS'
};
