import './features/modeling/ElementFactory';
import './features/modeling/Modeling';
import './features/modeling/cmd/UpdatePropertiesHandler';
import './features/palette/PaletteProvider';
import './features/popup-menu/ReplaceMenuProvider';
import './features/keyboard/BpmnKeyboardBindings';
import './features/label-editing/LabelEditingProvider';
import './features/command/CommandStack';
import './features/selection/Selection';
